In [1]:
%load_ext autoreload
%autoreload 2


In [2]:
from fasta_reader import FastaReader
fr = FastaReader("sample.fasta")
print(fr.fasta_2_numeric_encoding(pad_mode='front').shape)

1 th sequence's shape is (197,)
2 th sequence's shape is (197,)
3 th sequence's shape is (197,)
4 th sequence's shape is (197,)
5 th sequence's shape is (197,)
(5, 197)


In [3]:
import numpy as np
a = [1, 2, 3, 4, 5]
np.pad(a, (2, 0), 'constant', constant_values=(0, 0))

array([0, 0, 1, 2, 3, 4, 5])

In [4]:
from FastaDataset import FastaDataset
fd = FastaDataset("sample.fasta", encoding_mode="one_hot")
fd.get_max_length()

(197, 172, 187)

In [5]:
fd.seq_to_numeric("ACI")

tensor([1, 2, 8])

In [6]:
print(fd.seq_2_tensor("ACI").shape)
fd.seq_2_tensor2("ACI").shape

torch.Size([3, 22])


torch.Size([3, 1, 22])

In [7]:
from torch.utils.data import Dataset, DataLoader
from FastaDataset import FastaDataset
fd = FastaDataset("sample.fasta", encoding_mode="one_hot", pad_mode='end')
dataloader = DataLoader(fd, batch_size=2,
                        shuffle=False, num_workers=1)

In [8]:
for i, embedding in enumerate(dataloader):
#     print(fd.ger_record(i))
    print(embedding.shape)
    

torch.Size([2, 197, 22])
torch.Size([2, 197, 22])
torch.Size([1, 197, 22])


In [9]:
import torch
import torch.nn.functional as F
x = torch.tensor([0, 1, 7])
F.one_hot(x, num_classes=22)
# torch.arange(0, 5) % 3

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])